---
deploy_path: "/var/crypti"
deploy_user: root
app_url: http://downloads.crypti.me/crypti-node/0.1.x/crypti-linux-0.1.7.zip
app_version: 0.1.7
blockchain_url: http://downloads.crypti.me/blockchains/blockchain.db.zip
servers: {}
accounts: {}
